### PR TITLE
Add `AssemblyBuild` record

### PR DESCRIPTION
**Pull request by letsbreelhere**

### CODE REVIEW

**Comment by letsbreelhere** [comment]
Hmm, this looks like it pulls in a bunch of new commits from the original repo. Should I just send a patch instead?

**Comment by greggroth** [comment]
Let me see if I can't merge in upstream changes.

**Comment by greggroth** [comment]
@breestanwyck I merged in `upstream/master` into my master.  Can you rebase your branch?

**Comment by letsbreelhere** [comment]
:+1:

**Pull request merged**
